server:
  port: 0

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

greeting:
  message: Welcome to the Simple E-Commerce.


